theme: jekyll-theme-minimal
title: ada-2023-project-beeradaventure46
description: Use the textual reviews of a beer review dataset to find for each beer how it was served (either bottle, can or draft) and find how it influences the tasting profile. Different serving styles may be adopted in different regions or for different types of beer.  The influence of the serving style could influence not only the appearance, but also the aroma, the palate or the taste.
show_downloads: True
navigation:
  - title: Home
    url: README
  - title: Dataset
    url: dataset
  - title: Repository
    url: https://github.com/epfl-ada/ada-2023-project-beeradaventure46
  - title: Example
    url: example
  
